### ISSUE TITLE
It throw 'TypeError: Cannot read property 'languages' of undefined ' when I execute 'yo jhipster-vuejs2'

### ISSUE THREAD

**Issue by tutuerhao** [pengiundev/generator-jhipster-vuejs#1]
As indicated by the title

**Comment by pengiundev** [comment]
That's because it's using a custom jhipster-generator which you can find as a module called jhipster-generator-x or you can just go and replace the files containing jhipster-generator-x with jhipster-generator

**Comment by XingxiaoLu** [comment]
> ![qq 20181203171228](https://user-images.githubusercontent.com/29938085/49428421-fa5e0200-f7e0-11e8-8816-fd40e5b600f7.png)
> 
> How should I solver the bug?My English is not good....

你需要使用jhipster-x，应该是jhipster的一个fork

**Comment by visto** [comment]
@tutuerhao 

Follow the steps:

```
$ mkdir my_microfrontend
$ cd my_microfrontend
$my_microfrontend> jhipster --skip-server --db --auth
```

```
? What is the base name of your application? swd_microfrontend

? Which *Framework* would you like to use for the client? React

? Would you like to enable *SASS* stylesheet preprocessor? Yes

? Would you like to enable internationalization support? Yes

? Please choose the native language of the application English

? Please choose additional languages to install German

? Besides JUnit and Jest, which testing frameworks would you like to use? 

? Would you like to install other generators from the JHipster Marketplace? No
```

```
$my_microfrontend> npm install -g generator-jhipster-x
$my_microfrontend> yarn add generator-jhipster-vuejs2 --latest
$my_microfrontend> yo jhipster-vuejs2
```
Now open my_microfrontend/.yo-rc.json and edit the second line from 

`"generator-jhipster"`
to
`"generator-jhipster-x"`

Now do:

`$my_microfrontend> yo jhipster-vuejs2`

4. Profit

**Comment by pengiundev** [comment]
You can also install generator-jhipster-x the same way as generator-jhipster and use the jhipster-x command from the beginning

**Comment by 62mkv** [comment]
the documentation in the Marketplace says, though, that `yo jhipster-vuejs2` command should be used in order to create an application. Can this be updated ?

**Comment by pengiundev** [comment]
Forgot to say that's done now
